lineColor: [0, 0.443, 1, 1]
visibleFreq: [0.248, 0.692]
octaves: 1
bend: 0
scale: 0.952
rotation: 0
centerX: 0
centerY: 0
width: 2.05
lineInterspace: 0.45
smoothness: 0.683
innerIntensity: 2
outerIntensity: 2